BEST = {
    'af': 'Beste',
    'am': 'ምርጥ',
    'ar': 'الأفضل',
    'az': 'Ən yaxşı',
    'be': 'Найлепшы',
    'bg': 'Най -добър',
    'bn': 'সেরা',
    'bs': 'Najbolje',
    'ca': 'La millor',
    'ceb': 'Labing maayo',
    'co': 'U megliu',
    'cs': 'Nejlepší',
    'cy': 'Gorau',
    'da': 'Bedst',
    'de': 'Am besten',
    'el': 'Καλύτερος',
    'en': 'Best',
    'eo': 'Plej bona',
    'es': 'Mejor',
    'et': 'Parim',
    'eu': 'Onena',
    'fa': 'بهترین',
    'fi': 'Parhaat',
    'fr': 'Meilleur',
    'fy': 'Bêst',
    'ga': 'Ar dóigh',
    'gd': 'As fheàrr',
    'gl': 'Mellor',
    'gu': 'શ્રેષ્ઠ',
    'ha': 'M',
    'haw': 'Maikaʻi loa',
    'he': 'הטוב ביותר',
    'hi': 'श्रेष्ठ',
    'hmn': 'Zoo tshaj plaws',
    'hr': 'Najbolje',
    'ht': 'Pi bon',
    'hu': 'Legjobb',
    'hy': 'Լավագույն',
    'id': 'Terbaik',
    'ig': 'Okacka mma',
    'is': 'Bestur',
    'it': 'Migliore',
    'iw': 'הטוב ביותר',
    'ja': '一番',
    'jw': 'Paling apik',
    'ka': 'საუკეთესო',
    'kk': 'Ең жақсы',
    'km': 'ល្អបមផុត',
    'kn': 'ಅತ್ಯುತ್ತಮ',
    'ko': '최고',
    'ku': 'Baştirîn',
    'ky': 'Мыкты',
    'la': 'Optimum',
    'lb': 'Gutt Nuecht',
    'lo': 'ດີ\u200bທີ່\u200bສຸດ',
    'lt': 'Geriausia',
    'lv': 'Labākais',
    'mg': 'Tsara indrindra',
    'mi': 'Te tino pai',
    'mk': 'Најдобро',
    'ml': 'ഉത്തമമായ',
    'mn': 'Хамгийн сайн',
    'mr': 'सर्वोत्कृष्ट',
    'ms': 'Terbaik',
    'mt': 'L-aħjar',
    'my': 'အကောင်းဆုး',
    'ne': 'सबभन्दा रामो',
    'nl': 'Het beste',
    'no': 'Beste',
    'ny': 'Wabwino kwambiri',
    'or': 'ସର୍ବୋତ୍ତମ',
    'pa': 'ਵਧੀਆ',
    'pl': 'To, co najlepsze',
    'ps': 'ښه',
    'pt': 'Melhor',
    'ro': 'Cel mai bun',
    'ru': 'Лучший',
    'sd': 'سٺو',
    'si': 'හොඳ',
    'sk': 'Najlepšie',
    'sl': 'Najboljše',
    'sm': 'Sili',
    'sn': 'Zvakanakisa',
    'so': 'Ugu sarreeya',
    'sq': 'Më i mirë',
    'sr': 'Најбољи',
    'st': 'Hantle haholo',
    'su': 'Pangsaéna',
    'sv': 'Bäst',
    'sw': 'Bora',
    'ta': 'சிறந்த',
    'te': 'ఉత్తమమైనది',
    'tg': 'Беҳтар',
    'th': 'ดีที่สุด',
    'tl': 'Pinakamahusay',
    'tr': 'En iyi',
    'ug': 'ئەڭ ياخشى',
    'uk': 'Найкращий',
    'ur': 'بہترین',
    'uz': 'Eng yaxshi',
    'vi': 'Tốt nhất',
    'xh': 'Eyona ilungileyo',
    'yi': 'בעסטער',
    'yo': 'Dara julọ',
    'zh-cn': '最好的',
    'zh-tw': '最好的',
    'zu': '-Hle kakhulu'}
