DESCRIPTION = {
    'af': 'Sluit aan by die nommers en kom by die 2048 -teël!',
    'am': 'ቁጥራቸውን ይቀላቀሉ እና ወደ 2048 ንጣፍ ይሂዱ!',
    'ar': 'انضم إلى الأرقام واحصل على البلاط 2048!',
    'az': 'Nömrələrə qoşulun və 2048 kafel əldə edin!',
    'be': 'Далучайцеся да нумароў і дабярыцеся да пліткі 2048 года!',
    'bg': 'Присъединете се към номерата и стигнете до плочката 2048!',
    'bn': 'সংখ্যাগুলিতে যোগদান করুন এবং 2048 টাইল পান!',
    'bs': 'Pridružite se brojevima i doći do pločica 2048!',
    'ca': 'Uniu -vos als números i arribeu a la rajola del 2048.',
    'ceb': 'Pag-apil sa mga numero ug pag-adto sa 2048 tile!',
    'co': 'Uniscite à i numeri è ghjunghje à u 2048 tile!',
    'cs': 'Připojte se k číslům a dostaňte se na dlaždici 2048!',
    'cy': "Ymunwch â'r rhifau a chyrraedd y deilsen 2048!",
    'da': 'Deltag i numrene og kom til flisen 2048!',
    'de': 'Schließen Sie sich den Zahlen an und erreichen Sie die 2048 '
          '-Fliese!',
    'el': 'Εγγραφείτε στους αριθμούς και φτάσετε στο 2048 Tile!',
    'en': 'Join the numbers and get to the 2048 Tile!',
    'eo': 'Aliĝu al la nombroj kaj iru al la 2048 kahelo!',
    'es': '¡Une los números y llega al mosaico 2048!',
    'et': 'Liituge numbritega ja minge 2048. aasta plaadile!',
    'eu': 'Sartu zenbakiak eta iritsi 2048 fitxara!',
    'fa': 'به شماره ها بپیوندید و به کاشی 2048 برسید!',
    'fi': 'Liity numeroihin ja päästä 2048 -laattaan!',
    'fr': 'Rejoignez les chiffres et accédez à la tuile 2048!',
    'fy': 'Doch mei oan de sifers en kom nei de tegel fan 2048!',
    'ga': 'Bí ar na huimhreacha agus téigh go dtí an tíl 2048!',
    'gd': 'Thig còmhla ris na h-àireamhan agus faighinn chun t-leacag 2048!',
    'gl': 'Únete aos números e chega á tella 2048.',
    'gu': 'નંબરોમાં જોડાઓ અને 2048 ટાઇલ પર જાઓ!',
    'ha': 'Shiga lambobi kuma ka isa zuwa tayal 2048!',
    'haw': 'E hui pū me nā helu a loaʻa i ka 2048 tile!',
    'he': 'הצטרפו למספרים והגיעו לאריח 2048!',
    'hi': 'संख्याओं में शामिल हों और 2048 टाइल पर जाएं!',
    'hmn': 'Koom nrog cov lej thiab mus txog 2048 nplais!',
    'hr': 'Pridružite se brojevima i dođite do pločice 2048!',
    'ht': 'Join nimewo yo epi pou yo jwenn nan mozayik la 2048!',
    'hu': 'Csatlakozzon a számokhoz, és menjen a 2048 -as csempéhez!',
    'hy': 'Միացեք համարներին եւ հասեք 2048 կղմինդրին:',
    'id': 'Bergabunglah dengan angka dan dapatkan ubin 2048!',
    'ig': 'Soro nọmba ahụ wee rute 2048 taịlị!',
    'is': 'Vertu með í tölunum og komdu í 2048 flísarnar!',
    'it': 'Unisciti ai numeri e raggiungi la piastrella 2048!',
    'iw': 'הצטרפו למספרים והגיעו לאריח 2048!',
    'ja': '数字に参加して、2048タイルにアクセスしてください！',
    'jw': 'Gabung nomer lan entuk jubin 2048!',
    'ka': 'შემოგვიერთდით ნომრებზე და მიიღეთ 2048 წლის ფილაზე!',
    'kk': 'Сандарға қосылыңыз және 2048 қатарына жетіңіз!',
    'km': 'ចូលរួមលេខនិងទទួលបាន 2048 ក្រឡា!',
    'kn': 'ಸಂಖ್ಯೆಗಳಿಗೆ ಸೇರಿ ಮತ್ತು 2048 ಟೈಲ್\u200cಗೆ ಹೋಗಿ!',
    'ko': '숫자에 가입하고 2048 타일로 가십시오!',
    'ku': 'Bi hejmaran re tevlî bibin û biçin 2048 Tile!',
    'ky': 'Сандарга кошулуңуз жана 2048 плитка барыңыз!',
    'la': 'Iungere ad numerum et ad MMXLVIII Tile!',
    'lb': 'Maacht mat der Zuelen an kommt op den 2048 TAILE!',
    'lo': 'ເຂົ້າຮ່ວມໃນຕົວເລກແລະເຂົ້າໄປໃນກະເບື້ອງ 2048!',
    'lt': 'Prisijunkite prie numerių ir pateksite į 2048 m. Plytelę!',
    'lv': 'Pievienojieties skaitļiem un nokļūstiet 2048. gada flīzē!',
    'mg': "Midira ao amin'ny isa ary tongava amin'ny boaty 2048!",
    'mi': 'Whakauru atu ki nga nama ka tae ki te Tile 2048!',
    'mk': 'Придружете се на броевите и стигнете до плочката од 2048 година!',
    'ml': 'അക്കങ്ങളിൽ ചേരുക, 2048 ടൈലിലേക്ക് പോകുക!',
    'mn': 'Тоонуудтай нэгдээрэй, 2048 оны хавтан дээр очоорой!',
    'mr': 'नंबरमध्ये सामील व्हा आणि 2048 टाइलवर जा!',
    'ms': 'Sertai nombor dan sampai ke jubin 2048!',
    'mt': 'Ingħaqad man-numri u wasal għall-maduma 2048!',
    'my': 'နံပါတ်မျးကိုဆက်သွယ်ပြး 2048 tile ကိုရယူပါ။',
    'ne': 'नम्बरहरू सामेल हुनुहोस् र 204848 छोलीमा जानुहोस्!',
    'nl': 'Doe mee met de nummers en ga naar de Tile 2048!',
    'no': 'Bli med på tallene og kom til 2048 -flisen!',
    'ny': 'Lowani manambala ndikufika pa 2048 tile!',
    'or': 'ସଂଖ୍ୟାରେ ଯୋଗ ଦିଅନ୍ତୁ ଏବଂ 2048 ଟାଇଲ୍ କୁ ଯାଆନ୍ତୁ!',
    'pa': 'ਨੰਬਰਾਂ ਵਿੱਚ ਸ਼ਾਮਲ ਹੋਵੋ ਅਤੇ 2048 ਟਾਈਲ ਤੇ ਜਾਓ!',
    'pl': 'Dołącz do liczb i przejdź do kafelka 2048!',
    'ps': 'په شمیرو کې ګډون وکړئ او 2048 ټایل ته ورشئ!',
    'pt': 'Junte -se aos números e chegue ao azulejo 2048!',
    'ro': 'Alăturați -vă numerelor și ajungeți la țiglă 2048!',
    'ru': 'Присоединяйтесь к числам и доберитесь до плитки 2048 года!',
    'sd': 'انگن ۾ شامل ٿيو ۽ 2048 ٽائل تي وڃو!',
    'si': 'අංකවලට සම්බන්ධ වී 2048 ටයිල් එකකට යන්න!',
    'sk': 'Pripojte sa k číslam a dostaňte sa na dlaždicu 2048!',
    'sl': 'Pridružite se številkam in pridite do ploščice 2048!',
    'sm': 'Auai i fuainumera ma alu i le 2048 Tile!',
    'sn': 'Joinha nhamba uye usvike kuna 2048 Tile!',
    'so': 'Ku soo biir lambarrada oo gal tile 2048!',
    'sq': 'Bashkohuni me numrat dhe shkoni në pllakën 2048!',
    'sr': 'Придружите се бројевима и дођите до плочице 2048!',
    'st': "ENA ea linomoro 'me u fihle ho Tile ea 2048!",
    'su': 'Miluan nomer sareng dugi ka 2048 ubin!',
    'sv': 'Gå med i siffrorna och komma till 2048 -plattan!',
    'sw': 'Jiunge na nambari na ufikie kwenye tile 2048!',
    'ta': 'எண்களில் சேர்ந்து 2048 ஓடுக்குச் செல்லுங்கள்!',
    'te': 'సంఖ్యలలో చేరండి మరియు 2048 టైల్ పొందండి!',
    'tg': 'Ба рақамҳо ҳамроҳ шавед ва ба 2048 ворид шавед!',
    'th': 'เข้าร่วมหมายเลขและไปที่กระเบื้อง 2048!',
    'tl': 'Sumali sa mga numero at makarating sa 2048 tile!',
    'tr': 'Sayılara katılın ve 2048 karosuna gidin!',
    'ug': 'سانغا قوشۇلۇڭ ۋە 2048 كاھىشلارغا ئېرىشىڭ!',
    'uk': 'Приєднуйтесь до номерів і дістайтеся до плитки 2048 року!',
    'ur': 'نمبروں میں شامل ہوں اور 2048 ٹائل پر جائیں!',
    'uz': "Raqamlarga qo'shiling va 2048 plitkaga o'ting!",
    'vi': 'Tham gia các con số và đến Gạch 2048!',
    'xh': 'Joyina amanani kwaye ufumane kwi-2048 tele!',
    'yi': 'פאַרבינדן די נומערן און באַקומען צו 2048 קאַכל!',
    'yo': 'Darapọ mọ awọn nọmba ki o gba si Tile 2048!',
    'zh-cn': '加入数字，到达2048瓷砖！',
    'zh-tw': '加入數字，到達2048瓷磚！',
    'zu': 'Joyina izinombolo bese ufika ku-2048 tile!'}
