EXIT = {
    'af': 'Uitgaan',
    'am': 'ውጣ',
    'ar': 'مخرج',
    'az': 'Çıxmaq',
    'be': 'Выхадзіць',
    'bg': 'Изход',
    'bn': 'প্রস্থান',
    'bs': 'Izlaz',
    'ca': 'Abandonar',
    'ceb': 'Mogawas',
    'co': 'Surtita',
    'cs': 'Výstup',
    'cy': 'Allanfa',
    'da': 'Afslut',
    'de': 'Ausgang',
    'el': 'Εξοδος',
    'en': 'Exit',
    'eo': 'Eliru',
    'es': 'Salida',
    'et': 'Väljumine',
    'eu': 'Irteera',
    'fa': 'خروج',
    'fi': 'Poistuminen',
    'fr': 'Sortir',
    'fy': 'Útgong',
    'ga': 'An slí amach',
    'gd': 'Fàgail',
    'gl': 'Saír',
    'gu': 'બહાર નીકળવું',
    'ha': 'Fita',
    'haw': 'Ke puka nei',
    'he': 'יְצִיאָה',
    'hi': 'बाहर निकलना',
    'hmn': 'Tawm',
    'hr': 'Izlaz ',
    'ht': 'Sòti',
    'hu': 'Kijárat',
    'hy': 'Ելք',
    'id': 'KELUAR',
    'ig': 'Ụzọ ọpụpụ',
    'is': 'Hætta',
    'it': 'Uscita',
    'iw': 'יְצִיאָה',
    'ja': '出口',
    'jw': 'Metu',
    'ka': 'გასასვლელი',
    'kk': 'Шығу',
    'km': 'ចេញ',
    'kn': 'ನಿರ್ಗಮನ',
    'ko': '출구',
    'ku': 'Derî',
    'ky': 'Чыгуу',
    'la': 'Exitus',
    'lb': 'Stonneplang',
    'lo': 'ອອກໄປ',
    'lt': 'Išvažiavimas',
    'lv': 'Izeja',
    'mg': 'Fivoahana',
    'mi': 'Putanga',
    'mk': 'Излез',
    'ml': 'പുറത്ത്',
    'mn': 'гарах',
    'mr': 'बाहेर पडा',
    'ms': 'Keluar',
    'mt': 'Ħruġ',
    'my': 'ထွက်ပေါက်',
    'ne': 'प्रस्थान गर्नु',
    'nl': 'Uitgang',
    'no': 'Exit',
    'ny': 'Potulukira',
    'or': 'ପ୍ରସ୍ଥାନ',
    'pa': 'ਨਿਕਾਸ',
    'pl': 'Wyjście',
    'ps': 'وتون',
    'pt': 'Saída',
    'ro': 'Ieșire',
    'ru': 'Выход',
    'sd': 'ٻاهر ننا',
    'si': 'පිටවීම',
    'sk': 'VÝCHOD',
    'sl': 'Izhod',
    'sm': 'Ulufafo',
    'sn': 'Kubuda',
    'so': 'Bixitaan',
    'sq': 'Dalje',
    'sr': 'Излаз',
    'st': 'Etsoa',
    'su': 'Kaluar',
    'sv': 'Utgång',
    'sw': 'Utgång',
    'ta': 'வெளியேறு',
    'te': 'బయటకి దారి',
    'tg': 'Баромадгоҳ',
    'th': 'การออก',
    'tl': 'Lumabas',
    'tr': 'çıkış',
    'ug': 'چىقىش',
    'uk': 'Вихід',
    'ur': 'باہر نکلیں',
    'uz': 'Chiqish',
    'vi': 'Lối ra',
    'xh': 'Phuma',
    'yi': 'אַרויסגאַנג',
    'yo': 'Jade',
    'zh-cn': '出口',
    'zh-tw': '出口',
    'zu': 'Phuma'}
