KEEP_GOING = {
    'af': 'Hou aan',
    'am': 'ሂዱ',
    'ar': 'واصل التقدم',
    'az': 'Davam et',
    'be': 'Працягваць',
    'bg': 'Продължавай',
    'bn': 'চোলতে থাকা',
    'bs': 'Nastavi',
    'ca': 'Seguiu endavant',
    'ceb': 'Padayon',
    'co': 'Cuntinuà',
    'cs': 'Pokračuj',
    'cy': 'Daliwch ati',
    'da': 'Fortsæt',
    'de': 'Weitermachen',
    'el': 'Συνέχισε',
    'en': 'Keep going',
    'eo': 'Daŭrigu',
    'es': 'Sigue adelante',
    'et': 'Jätka',
    'eu': 'Jarrai',
    'fa': 'ادامه دادن',
    'fi': 'Pysy menossa',
    'fr': 'Continue',
    'fy': 'Trochgean',
    'ga': 'Coinnigh ar siúl',
    'gd': "Cùm a 'dol",
    'gl': 'Seguir adiante',
    'gu': 'ચાલુ રાખો',
    'ha': 'Ci gaba da tafiya',
    'haw': 'Hoʻomau',
    'he': 'תמשיך ללכת',
    'hi': 'बढ़ा चल',
    'hmn': 'Cia li mus',
    'hr': 'Nastavi',
    'ht': 'Kontinye',
    'hu': 'Folytasd',
    'hy': 'Շարունակիր',
    'id': 'Terus berlanjut',
    'ig': 'Na-aga',
    'is': 'Haltu áfram',
    'it': 'Continuare',
    'iw': 'תמשיך ללכת',
    'ja': '立ち止まるな',
    'jw': 'Terus maju',
    'ka': 'Განაგრძე',
    'kk': 'Жалғастыру',
    'km': 'បន្ត\u200bទៀត',
    'kn': 'ಹೇಗ್ತಾ ಇರು',
    'ko': '계속하라',
    'ku': 'Berdewam kirin',
    'ky': 'Уланта бер',
    'la': 'Perserva',
    'lb': 'Loss dech net ënnerkréien',
    'lo': 'ສືບຕໍ່ໄປ',
    'lt': 'Tęsk',
    'lv': 'Turpini',
    'mg': 'Tohizo hatrany',
    'mi': 'Haere tonu',
    'mk': 'Продолжи да одиш',
    'ml': 'പൊയ്ക്കൊണ്ടേയിരിക്കുന്നു',
    'mn': 'Нэвч шүүмжлэх',
    'mr': 'चालू ठेवा',
    'ms': 'Teruskan',
    'mt': "Ibqa 'għaddej",
    'my': 'ဆက်လုပ်ပါ',
    'ne': 'गरि राख',
    'nl': 'Ga zo door',
    'no': 'Fortsett',
    'ny': 'Pitiliranibe',
    'or': 'ଜାରି ରଖ',
    'pa': 'ਚੱਲਦੇ ਰਹੋ',
    'pl': 'Kontynuować',
    'ps': 'ځه',
    'pt': 'Continue',
    'ro': 'Continuă',
    'ru': 'Продолжать идти',
    'sd': 'جاري رکو',
    'si': 'දිගටම යන්න',
    'sk': 'Pokračuj',
    'sl': 'Nadaljuj',
    'sm': 'Faifai ai pea',
    'sn': 'Ramba uchienda',
    'so': 'Sii wad',
    'sq': 'Vazhdoj',
    'sr': 'Настави',
    'st': 'Tsoela pele',
    'su': 'Lajengkeun',
    'sv': 'Fortsätt',
    'sw': 'Endelea',
    'ta': 'தொடர்ந்து செல்லுங்கள்',
    'te': 'కొనసాగించండి',
    'tg': 'Рафтанро давом диҳед',
    'th': 'ทำต่อไป',
    'tl': 'Tuloy lang',
    'tr': 'Devam et',
    'ug': 'داۋاملاشتۇرۇش',
    'uk': 'Продовжуй',
    'ur': 'چلتے رہو',
    'uz': 'Yurishda davom eting',
    'vi': 'Tiếp tục đi',
    'xh': 'Qhubeka uhamba',
    'yi': 'גיי אן',
    'yo': 'Tẹsiwaju laisi idiwọ',
    'zh-cn': '继续',
    'zh-tw': '繼續',
    'zu': 'Qhubeka'}
