LOSE = {
    'af': 'Jy het verloor',
    'am': 'ጠፋሽ',
    'ar': 'كنت قد فقدت',
    'az': 'İtirdin',
    'be': 'Вы прайгралі',
    'bg': 'Загубихте',
    'bn': 'আপনি হারিয়েছেন',
    'bs': 'Izgubili ste se',
    'ca': 'Has perdut',
    'ceb': 'Nawala ka',
    'co': 'Avete persu',
    'cs': 'Ztratil jsi',
    'cy': 'Rydych chi wedi colli',
    'da': 'Du har mistet',
    'de': 'Du hast verloren',
    'el': 'Έχετε χάσει',
    'en': "You've lost",
    'eo': 'Vi perdis',
    'es': 'Has perdido',
    'et': 'Sa oled kaotanud',
    'eu': 'Galdu duzu',
    'fa': 'شما از دست داده اید',
    'fi': 'Olet kadonnut',
    'fr': 'Tu as perdu',
    'fy': 'Do hast ferlern',
    'ga': 'Tá tú caillte',
    'gd': 'Tha thu air chall',
    'gl': 'Perdiches',
    'gu': 'તમે ખોવાઈ ગયા છો',
    'ha': 'Kun rasa',
    'haw': 'Ua nalowaleʻoe',
    'he': 'הפסדת',
    'hi': 'यू हैव लॉस्ट',
    'hmn': 'Koj twb tau ploj',
    'hr': 'Izgubili ste',
    'ht': 'Ou pèdi',
    'hu': 'Elvesztettél',
    'hy': 'Դուք կորցրել եք',
    'id': 'Anda telah kalah',
    'ig': 'Ị furu efu',
    'is': 'Þú hefur tapað',
    'it': 'Hai perso',
    'iw': 'הפסדת',
    'ja': 'あなたは負けました',
    'jw': 'Sampeyan wis ilang',
    'ka': 'შენ დაკარგე',
    'kk': 'Сіз жоғалттыңыз',
    'km': 'អ្នកបានបាត់បង់',
    'kn': 'ನೀವು ಕಳೆದುಹೋಗಿದ್ದೀರಿ',
    'ko': '당신은 잃어 버렸습니다',
    'ku': 'We winda kiriye',
    'ky': 'Сен жоголдуң',
    'la': 'Tu perdidit',
    'lb': 'Du hues verluer',
    'lo': 'ທ່ານໄດ້ສູນເສຍ',
    'lt': 'Jūs pralaimėjote',
    'lv': 'Tu esi pazaudējis',
    'mg': 'Very ianao',
    'mi': 'Kua ngaro koe',
    'mk': 'Вие изгубивте',
    'ml': 'നിങ്ങൾ നഷ്ടപ്പെട്ടു',
    'mn': 'Та алдсан',
    'mr': 'आपण हरवले',
    'ms': 'Anda telah kehilangan',
    'mt': 'Tlift',
    'my': 'သင်ရှးပြီ',
    'ne': 'हराउनु भयो',
    'nl': 'Je hebt verloren',
    'no': 'Du har mistet',
    'ny': 'Mwataya',
    'or': 'ତୁମେ ହଜିଯାଇଛ',
    'pa': 'ਤੁਸੀਂ ਗੁਆ ਚੁੱਕੇ ਹੋ',
    'pl': 'Straciłeś',
    'ps': 'تا له لاسه ورکړ',
    'pt': 'Você perdeu',
    'ro': 'Ai pierdut',
    'ru': 'Вы проиграли',
    'sd': 'توهان وڃائي ڇڏيو آهي',
    'si': 'ඔබට අහිමි වී ඇත',
    'sk': 'Stratil si',
    'sl': 'Izgubili ste',
    'sm': 'Ua e leiloa',
    'sn': 'Warasikirwa',
    'so': 'Waad lumisay',
    'sq': 'Ju keni humbur',
    'sr': 'Изгубио си',
    'st': 'O lahlile',
    'su': 'Anjeun Kaleungitan',
    'sv': 'Du har tappat',
    'sw': 'Umepoteza',
    'ta': 'நீங்கள் இழந்துவிட்டீர்கள்',
    'te': 'మీరు ఓడిపోయారు',
    'tg': 'Шумо гум кардед',
    'th': 'คุณหลงทาง',
    'tl': 'Nawala ka',
    'tr': 'Kaybettin',
    'ug': 'يۈتۈپ كەتتىڭىز',
    'uk': 'Ти загубився',
    'ur': 'تم ہار گئے ہو',
    'uz': 'Siz yutqazdingiz',
    'vi': 'Bạn đã mất',
    'xh': 'Ulahlekile',
    'yi': "איר'ווע פאַרפאַלן",
    'yo': 'O ti padanu',
    'zh-cn': '你迷路了',
    'zh-tw': '你迷路了',
    'zu': 'Ulahlekile'}
