NEW_GAME = {
    'af': 'Nuwe spel',
    'am': 'አዲስ ጨዋታ',
    'ar': 'لعبة جديدة',
    'az': 'Yeni oyun',
    'be': 'Новая гульня',
    'bg': 'Нова игра',
    'bn': 'নতুন খেলা',
    'bs': 'Nova igra',
    'ca': 'Nou joc',
    'ceb': 'Bag-ong Dula',
    'co': 'Novu ghjocu',
    'cs': 'Nová hra',
    'cy': 'Gêm newydd',
    'da': 'Nyt spil',
    'de': 'Neues Spiel',
    'el': 'Νέο παιχνίδι',
    'en': 'New game',
    'eo': 'Nova Ludo',
    'es': 'Nuevo juego',
    'et': 'Uus mäng',
    'eu': 'Joko berria',
    'fa': 'بازی جدید',
    'fi': 'Uusi peli',
    'fr': 'Nouveau jeu',
    'fy': 'Nij spultsje',
    'ga': 'Cluiche nua',
    'gd': 'Gèam ùr',
    'gl': 'Novo xogo',
    'gu': 'નવી રમત',
    'ha': 'Sabuwar Wasan',
    'haw': 'Pāʻani hou',
    'he': 'משחק חדש',
    'hi': 'नया खेल',
    'hmn': 'Kev Ua Si Tshiab',
    'hr': 'Nova igra',
    'ht': 'Nouvo jwèt',
    'hu': 'Új játék',
    'hy': 'Նոր խաղ',
    'id': 'Permainan baru',
    'ig': 'Egwuregwu ọhụrụ',
    'is': 'Nýr leikur',
    'it': 'Nuovo gioco',
    'iw': 'משחק חדש',
    'ja': '新しいゲーム',
    'jw': 'Game Anyar',
    'ka': 'ახალი თამაში',
    'kk': 'Жаңа ойын',
    'km': 'ល្បែង\u200bថ្មី',
    'kn': 'ಹೊಸ ಆಟ',
    'ko': '새로운 게임',
    'ku': 'Lîstika nû',
    'ky': 'Жаңы оюн',
    'la': 'Novum ludum',
    'lb': 'Neie Game',
    'lo': 'ເກມ\u200bໃຫມ່',
    'lt': 'Naujas žaidimas',
    'lv': 'Jauna spēle',
    'mg': 'Lalao vaovao',
    'mi': 'Kēmu hou',
    'mk': 'Нова игра',
    'ml': 'പുതിയ ഗെയിം',
    'mn': 'Шинэ тоглоом',
    'mr': 'नवीन खेळ',
    'ms': 'Permainan baru',
    'mt': 'Logħba Ġdida',
    'my': 'ဂိမ်းအသစ်',
    'ne': 'नयाँ खेल',
    'nl': 'Nieuw spel',
    'no': 'Nytt spill',
    'ny': 'Masewera Atsopano',
    'or': 'ନୂତନ ଖେଳ',
    'pa': 'ਨਵੀਂ ਖੇਡ',
    'pl': 'Nowa gra',
    'ps': 'نوی لوبه',
    'pt': 'Novo jogo',
    'ro': 'Joc nou',
    'ru': 'Новая игра',
    'sd': 'نئين راند',
    'si': 'නව ක්රීඩාව',
    'sk': 'Nová hra',
    'sl': 'Nova igra',
    'sm': 'Taaloga fou',
    'sn': 'Mutambo mutsva',
    'so': 'Ciyaar cusub',
    'sq': 'Lojë e re',
    'sr': 'Нова игра',
    'st': 'Papali e Ncha',
    'su': 'Game anyar',
    'sv': 'Nytt spel',
    'sw': 'Mchezo mpya',
    'ta': 'புதிய விளையாட்டு',
    'te': 'కొత్త ఆట',
    'tg': 'Бозии нав',
    'th': 'เกมส์ใหม่',
    'tl': 'Bagong laro',
    'tr': 'Yeni oyun',
    'ug': 'يېڭى ئويۇن',
    'uk': 'Нова гра',
    'ur': 'نیا کھیل',
    'uz': "Yangi o'yin",
    'vi': 'Trò chơi mới',
    'xh': 'Umdlalo omtsha',
    'yi': 'ניו שפּיל',
    'yo': 'Ere titun',
    'zh-cn': '新游戏',
    'zh-tw': '新遊戲',
    'zu': 'Umdlalo omusha'}
