WIN = {
    'af': 'Jy het gewen',
    'am': 'አሸንፈሃል',
    'ar': 'لقد ربحت',
    'az': 'Qazandınız',
    'be': 'Вы выйгралі',
    'bg': 'Вие сте спечелили',
    'bn': 'তুমি জিতেছ',
    'bs': 'Pobijedili ste',
    'ca': 'Has guanyat',
    'ceb': 'Nagdaug ka',
    'co': 'Avete vintu',
    'cs': 'Vyhrál jsi',
    'cy': 'Rydych chi wedi ennill',
    'da': 'Du har vundet',
    'de': 'Du hast gewonnen',
    'el': 'Έχετε κερδίσει',
    'en': "You've won",
    'eo': 'Vi gajnis',
    'es': 'Has ganado',
    'et': 'Sa oled võitnud',
    'eu': 'Irabazi duzu',
    'fa': 'شما برنده اید',
    'fi': 'Olet voittanut',
    'fr': 'Vous avez gagné',
    'fy': 'Jo hawwe wûn',
    'ga': 'Bhuaigh tú',
    'gd': 'Tha thu air buannachadh',
    'gl': 'Gañaches',
    'gu': 'તમે જીતી ગયા છો',
    'ha': 'Kun yi nasara',
    'haw': 'Ua lanakilaʻoe',
    'he': 'ניצחת',
    'hi': 'आप जीत गए',
    'hmn': 'Koj twb yeej lawm',
    'hr': 'Osvojili ste',
    'ht': 'Ou te genyen',
    'hu': 'Nyertél',
    'hy': 'Դուք հաղթել եք',
    'id': 'Anda telah menang',
    'ig': 'Ị meriela',
    'is': 'Þú hefur unnið',
    'it': 'Hai vinto',
    'iw': 'ניצחת',
    'ja': 'あなたは勝ちました',
    'jw': 'Sampeyan wis menang',
    'ka': 'თქვენ მოიგეთ',
    'kk': 'Сіз жеңдіңіз',
    'km': 'អ្នកបានឈ្នះ',
    'kn': 'ನೀವು ಗೆದ್ದಿದ್ದೀರಿ',
    'ko': '당신은 이겼습니다',
    'ku': 'We qezenc kir',
    'ky': 'Сен жеңдиң',
    'la': 'Tu vicit',
    'lb': 'Dir hutt gewonnen',
    'lo': 'ທ່ານໄດ້ຊະນະແລ້ວ',
    'lt': 'Jūs laimėjote',
    'lv': 'Jūs esat uzvarējis',
    'mg': 'Nandresy ianao',
    'mi': 'Kua wikitoria koe',
    'mk': 'Сте победиле',
    'ml': 'നിങ്ങൾ വിജയിച്ചു',
    'mn': 'Та яллаа',
    'mr': 'आपण जिंकले',
    'ms': 'Anda telah menang',
    'mt': 'Int rebaħ',
    'my': 'မင်းအနိုင်ရပြီ',
    'ne': 'लिनु भएको थियो',
    'nl': 'Je hebt gewonnen',
    'no': 'Du har vunnet',
    'ny': 'Mwapambana',
    'or': 'ତୁମେ ଜିତିଲ',
    'pa': 'ਤੁਸੀਂ ਜਿੱਤ ਗਏ ਹੋ',
    'pl': 'Wygrałeś',
    'ps': 'تاسو وګټله',
    'pt': 'Você ganhou',
    'ro': 'Ai câștigat',
    'ru': 'Вы выиграли',
    'sd': 'توهان کٽيو آهي',
    'si': 'ඔබ දිනුවා',
    'sk': 'Vyhral si',
    'sl': 'Zmagali ste',
    'sm': 'Ua e manumalo',
    'sn': 'Wakunda',
    'so': 'Waad guuleysatay',
    'sq': 'Ju keni fituar',
    'sr': 'Победио си',
    'st': 'O hapile',
    'su': 'Anjeun meunang',
    'sv': 'Du har vunnit',
    'sw': 'Umeshinda',
    'ta': 'நீங்கள் வென்றீர்கள்',
    'te': 'మీరు గెలిచారు',
    'tg': 'Шумо ғолиб кардед',
    'th': 'คุณชนะ',
    'tl': 'Nanalo ka',
    'tr': 'Sen kazandın',
    'ug': 'سىز غەلىبە قىلدىڭىز',
    'uk': 'Ви виграли',
    'ur': 'آپ جیت گئے ہیں',
    'uz': 'Siz yutdingiz',
    'vi': 'Bạn thắng rồi',
    'xh': 'Uphumelele',
    'yi': 'איר וואַן',
    'yo': 'O ti bori',
    'zh-cn': '你赢了',
    'zh-tw': '你贏了',
    'zu': 'Unqobile'}
